//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_Search_Path_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI_Search_Path_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _420 {
            get {
                object obj = ResourceManager.GetObject("_420", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accra		Ghana
        ///Addis Ababa	Ethiopa
        ///Adelaide	Australia
        ///Aden		South Yemen
        ///Alexandria	Egypt
        ///Algiers		Algeria
        ///Amsterdam	Netherland
        ///Ankara		Turkey
        ///Athens		Greece
        ///Auckland	New Zealand
        ///Baghdad		Iraq
        ///Bahrain		Bahrain
        ///Baltimore	USA
        ///Bandung		Indonesia
        ///Bangkok		Thailand
        ///Barbados	West Indies
        ///Beijing		China
        ///Beirut		Lebanon
        ///Belgrade	Yugoslavia
        ///Berlin		Germany
        ///Bermuda		Bermuda
        ///Berne		Switzerland
        ///Bissau		Guinea-Bissau
        ///Bogota		Colombia
        ///Bombay		India
        ///Boston		USA
        ///Brazzaville	Congo
        ///Brisbane	Australia
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string places {
            get {
                return ResourceManager.GetString("places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arad 366 Zerind 75 Timisoara 118 Sibiu 140
        ///Bucharest 0 Giurgiu 90 Pitesti 101 Fagaras 211 Urziceni 85
        ///Craiova 160 Dobreta 120 Rimnicu_Vilcea 146 Pitesti 138
        ///Dobreta 242 Craiova 120 Mehadia 75
        ///Eforie 161 Hirsova 86
        ///Fagaras 176 Sibiu 99 Bucharest 211
        ///Giurgiu 77 Bucharest 90
        ///Hirsova 151 Eforie 86 Urziceni 98
        ///Iasi 226 Neamt 87 Vaslui 92
        ///Lugoj 244 Timisoara111 Mehadia 70
        ///Mehadia 241 Lugoj 70 Dobreta 75
        ///Neamt 234 Iasi 87
        ///Oradea 380 Zerind 71 Sibiu 151
        ///Pitesti 101 Rimnicu_Vilcea 97 Craiova 138 Buchare [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap w {
            get {
                object obj = ResourceManager.GetObject("w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
